### ISSUE TITLE
dead project?

### ISSUE THREAD

**Issue by pythonmobile** [openid/python-openid#62]
The last update on pypy was in 2010. Are there any plans for a new version -- at least bug fixes?

**Comment by flying-sheep** [comment]
the [python3-openid](https://github.com/necaris/python3-openid) project isn’t though, so you could simply give its author commit rights here and let him update this with his fixes

**Comment by willnorris** [comment]
Sure, if the python3-openid authors are interested, I can add them here.

**Comment by flying-sheep** [comment]
hi @necaris, are you?

**Comment by ziima** [comment]
Hi, I've been putting the library together in [my fork](/ziima/python-openid) for some time now. I'd be glad to upload the changes into upstream and it looks like, I'll be able to maintain the library for a while, since I'm going for Python2/3 support.

**Comment by necaris** [comment]
@willnorris @flying-sheep are you able to give me / @ziima the ability to upload new versions to PyPI?

**Comment by ziima** [comment]
@necaris: Hi, I'm not. I looked at it, but it contained too many commits for me to be able to cherry-pick any of those. I started with cleanup of the library itself before I can add Python 3 support. Anyhow, if you can provide a pull requests towards the Python 3 support, you might save me some work :)

**Comment by necaris** [comment]
@ziima In the process of making it Python-3 compatible some cleanup had to occur, so that is included in [python3-openid]( https://github.com/necaris/python3-openid). I am not very excited to rebase all that work on top of yours, though. 

Conversely, [I have an issue open](https://github.com/necaris/python3-openid/issues/32) for Python 2.7 support, so if you were willing to help with that, we could converge there.

**Comment by ziima** [comment]
@necaris: I'm not very excited to return Python2.7 support into a project which already dropped it either. Still hope, we can figure something out.

**Comment by necaris** [comment]
@ziima Indeed, it seems like a step backwards to add Python2 support.

**Comment by flying-sheep** [comment]
it’s possible to make a clean switch, so that python 2 users still get the latest python2-supporting version when `pip install`ing: https://stackoverflow.com/questions/40114100/uploading-different-versions-python-2-7-vs-3-5-to-pypi

if the current version gets a `Requires-Python: 2.7` field and the replacement gets `Requires-Python: >=3.5` or so, everyone is happy.

together with a major version change, API breakage will also not confuse anyone.

**Comment by necaris** [comment]
@flying-sheep since [python3-openid]( https://github.com/necaris/python3-openid) doesn't support Python 2, that seems like it would mean:
 - a new PyPI release from here, with the appropriate `Requires` statements in `setup.py`
 - merging upstream Python 3 support, from @ziima's work or mine or both, as a new major version 
 - a new release as the Python 3-only version
 - only supporting Python 3 going forward for the new version (after all, it's 2018) but possibly backporting cleanups to the older version branch 

Does that sound right? Is that acceptable to all? If so, I'm 👍 and happy to help with it, if I can get access to this and the PyPI credentials as well.

**Comment by ziima** [comment]
I'm not sure `python3-openid` keeps the API. I had to add some backward compatibility into master to match API in 2.2.5.

**Comment by necaris** [comment]
There are some API differences in `python3-openid`, that's true -- partly because Python 3 and Python 2.3 (as supported by this package) are really not compatible, but also partly because I haven't made a concerted effort to match any recent updates.

**Comment by willnorris** [comment]
> @willnorris @flying-sheep are you able to give me / @ziima the ability to upload new versions to PyPI?

I no longer have access to the OpenID org on GitHub, and don't think I ever had access to the PyPI package, so am not going to be able to help here.  Sorry.

**Comment by flying-sheep** [comment]
and i never had anything of the like, sorry!

**Comment by necaris** [comment]
On Sun, Jan 28, 2018 at 10:56:52AM +0000, Philipp A. wrote:
>and i never had anything of the like, sorry!

So it sounds like we couldn't replace the existing PyPI package even if 
we wanted to! Since that's the case, I will probably be keeping my 
package Python 3 only unless I get help backporting it!

**Comment by flying-sheep** [comment]
we can file a request to pypi to take it over.

that happened with tqdm as well.

**Comment by ziima** [comment]
I don't think Pypi have any procedure to take over a project. They're super cautious after what happened with django-registration and I don't think they'll give access to anybody on any project anytime soon.

**Comment by flying-sheep** [comment]
as said: when the tqdm community recognized that the project owner didn’t react anymore, they asked to take over, created a community project and it became upstream tqdm.

**Comment by willnorris** [comment]
@tnarg: are you "tnarg" on PyPI as well?  If so, it looks like you're the owner of record of the python-openid package.  Could you help some of the folks here gain access to that so they can update it.  

You all may also need to talk to someone at the OpenID Foundation about taking over maintenance of the GitHub repo as well, since I don't know anymore who has access to it.  There used to be a code@openid.net mailing list, though I don't know if it's active anymore.

**Comment by ziima** [comment]
I've released python-openid2 3.0 with python3 support and as much compatibility with python-openid as possible.

**Comment by hugovk** [comment]
@ziima It's now possible to request the transfer of the PyPI name for an abandoned project via PEP 541. See: 

* https://www.python.org/dev/peps/pep-0541/#abandoned-projects

And file an issue here:

* https://github.com/pypa/pypi-support/issues/new?template=pep541-request.md

After a decade of no releases, I think it might be a good idea to transfer python-openid for your fork.

**Comment by necaris** [comment]
:+1: thanks for the info @hugovk ! @ziima's fork since it maintains Python 2 compatibility is probably a better option than `python3-openid` but I think either is better than an untouched project.

**Comment by ziima** [comment]
@hugovk: Transfer is already in process https://github.com/pypa/pypi-support/issues/496 I'm waiting for it to be finished.

**Comment by ziima** [comment]
Transfer complete. I'll try to transfer python-openid2 to python-openid is a reasonable time.
